id: IE9673411
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:27:37.689328
last_modified: 2023-01-04 11:27:37.689345
source_metadata:
  collections:
  - Adzom Gyalse Series
  - Works of Tibetan Masters
bases:
  D34F:
    title: A Concise Explanation of Gaṇacakra
    base_file: D34F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
